[package]
name = "weechat-macro"
version = "0.1.0"
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
libc = "0.2.68"
syn = "1.0.17"
proc-macro2 = "1.0.9"
quote = "1.0.3"
